### ISSUE TITLE
Package hls_utils

### ISSUE THREAD

**Issue by prakruti** [orcasound/aifororcas-livesystem#53]
Also, take the opportunity to refactor https://github.com/orcasound/aifororcas-livesystem/tree/main/InferenceSystem/src/hls_utils

**Comment by Molkree** [comment]
Test repo: https://github.com/Molkree/orcasound-hls-utils
Package on Test PyPI: https://test.pypi.org/project/orcasound-hls-utils/

Some questions:
1. License: I've put MIT and I guess it's alright to keep it.
2. Build system: for now I've just copied stuff from [Packaging tutorial](https://packaging.python.org/tutorials/packaging-projects/), so it's `setuptools>=42` and `wheel`.
3. Readme: just put in two sentences, probably need to add more!
4. Metadata (in `setup.cfg`):
      1. What should be the package name? For now I've made it `orcasound-hls-utils` (this is what shows up on PyPI). Related to it is the package name (the one you use when importing in the code, `orcasound_hls_utils` now) and repository name (`orcasound-hls-utils` now).
      2. How will the versioning work? Right now the version is specified in the `setup.cfg`
      3. Who is the author? (left author/email with placeholders)
      4. Short description: "Collection of utilities for getting Orcasound HLS data" now.

I will transfer the repository under Orcasound organization when it's ready.

P.S. Oh, and I forgot to add `requirements.txt`, will do now 😅

@prakruti, am I moving in the right direction?

**Comment by prakruti** [comment]
Sounds great @Molkree! I was earlier wondering if it would be possible to publish from the livesystem repo itself but I guess this is the right thing to do is to create a separate repo for it. Thanks!

**Comment by Molkree** [comment]
So one of the next steps should be removing the code from this repo and instead using the package. I guess for that I'll need to run  InferenceSystem locally to test that everything works. Correct, @prakruti?

**Comment by Molkree** [comment]
> I guess for that I'll need to run InferenceSystem locally to test that everything works.

Had to fight with my installed Python versions a bit, I know it was only tested on 3.7 but couldn't stop trying newer:
- I had little hope that Python 3.10 on Win would work and it didn't because numpy can't be built, I have abandoned it.
- Python 3.9.5 in Ubuntu didn't work because pip can't find torchaudio==0.6.0 (maybe we should update it in the future)
- Python 3.8.10 worked after installing gcc and python3-dev (`sudo apt install gcc python3-dev`, note that my Ubuntu has 3.8 as default but you might need to specify `python3.8-dev`) and wheel (`python -m pip install wheel`)

Local inference worked fine after that.

Now to testing, I have just replaced `hls_utils.*` imports with `orca_hls_utils.*` imports and installed the package. After trying to run inference again I have discovered that I made a mistake in `orca-hls-utils` dependencies and added `python-ffmpeg` instead of `ffmpeg-python`. Both packages exist and they are incompatible! Funny thing is that I made the same mistake when I worked with ffmpeg from Python over this summer. So I have fixed this dependency in the package and released a new version 0.0.2. Everything seems to work correctly now.

I'll be sending PR removing the code from this repo and adding a new dependency tomorrow.
